function [dataCleaned, extract] = cleanTrials(data, opts)

opts.check();

% Do thresholding to get a slightly better estimate of start time
estimStartIndexThreshold = ERAASR.thresholdToFindApproximateOnset(data, opts.Fs, opts.thresholdValue, ... 
    'hpCornerHz', opts.thresholdHPCornerHz, 'thresholdChannel', opts.thresholdChannel);

if any(isnan(estimStartIndexThreshold))
    error('%d trials did not cross threshold', nnz(isnan(estimStartIndexThreshold)));
end

%% Do precision subsampling alignment and extract the window to clean as a tensor

% tensorAligned will be nTrials x extractWindowDuration x nChannels
[tensorAligned, extractIndStart] = ERAASR.preciseAlignExtractArtifacts(data, estimStartIndexThreshold, ...
    'alignUpsampleBy', opts.alignUpsampleBy, 'alignWindowPre', opts.alignWindowPre, ...
    'alignWindowDuration', opts.alignWindowDuration, 'alignChannel', opts.alignChannel, ...
    'extractWindowPre', opts.extractWindowPre, 'extractWindowDuration', opts.extractWindowDuration, ...
    'quiet', opts.quiet);

% number of samples before the first pulse starts in dataAligned
samplesPre = opts.extractWindowPre - opts.cleanStartSamplesPreThreshold;

%% Clean the artifact tensor using ERAASR

[tensorCleaned, extract] = ERAASR.cleanArtifactTensor(tensorAligned, opts.Fs, 'samplesPre', samplesPre, ...
    'hpCornerHz', opts.cleanHPCornerHz, 'hpOrder', opts.cleanHPOrder, ...
    'upsampleBy', opts.cleanUpsampleBy, ...
    'samplesPerPulse', opts.samplesPerPulse,  'nPulses', opts.nPulses, ...
    'nPC_channels', opts.nPC_channels, 'nPC_trials', opts.nPC_trials, 'nPC_pulses', opts.nPC_pulses, ...
    'omit_bandwidth_channels', opts.omit_bandwidth_channels, ...
    'omit_bandwidth_trials', opts.omit_bandwidth_trials, ...
    'omit_bandwidth_pulses', opts.omit_bandwidth_pulses, ...
    'alignPulsesOverTrain', opts.alignPulsesOverTrain, ...
    'pcaOnlyOmitted', opts.pcaOnlyOmitted, ...
    'cleanOverChannelsIndividualTrials', opts.cleanOverChannelsIndividualTrials, ...
    'cleanOverPulsesIndividualChannels', opts.cleanOverPulsesIndividualChannels, ...
    'cleanOverTrialsIndividualChannels', opts.cleanOverTrialsIndividualChannels, ...
    'cleanPostStim', opts.cleanPostStim, ...
    'showFigures', opts.showFigures, 'plotTrials', opts.plotTrials, 'plotPulses', opts.plotPulses, ...
    'saveFigures', opts.saveFigures, 'figurePath', opts.figurePath, 'saveFigureCommand', opts.saveFigureCommand, ...
    'quiet', opts.quiet);

%% Reinsert the cleaned tensor into the full trials

dataCleaned = ERAASR.reinsertTensorPreservingContinuity(data, tensorCleaned, extractIndStart);

%% Pass along metadata

extract.extractAlignedPreCleaning = tensorAligned;
extract.extractIndStart = extractIndStart;
extract.stimStart = samplesPre + extractIndStart; % will indicate the index at which the first pulse begins when splitting into tensor, includes cleanStartSamplesPreThreshold

end